import { Link, createFileRoute } from "@tanstack/react-router"

import { Badge } from "@workspace/ui/components/badge"
import { buttonVariants } from "@workspace/ui/components/button"
import { Card } from "@workspace/ui/components/card"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
} from "@workspace/ui/components/empty"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@workspace/ui/components/table"

import { AdminShell } from "@/components/admin/admin-shell"
import { ClientRowActions } from "@/components/admin/client-row-actions"
import { SecretDialog } from "@/components/common/dialogs"
import { FormRefusal } from "@/components/auth/form-parts"
import { NoticeToast } from "@/components/common/notice-toast"
import { crumbTrail } from "@/components/common/breadcrumbs"
import { messageForErrorCode, messageForNoticeCode } from "@/lib/auth-errors"
import { adminHead } from "@/lib/page-title"
import { searchString } from "@/lib/search-params"
import { getCatalog } from "@/server/i18n"
import { claimAdminSecret, fetchClients } from "@/server/functions/admin"
import {
  adminErrorCodeFor,
  callAuth,
  readForm,
  redirectWithCookies,
  withError,
} from "@/server/http/auth-proxy"
import { requireSession } from "@/server/http/require-session"
import { stash } from "@/server/http/one-shot"
import { getRuntime } from "@/server/runtime"

const HERE = "/admin/clients"

/**
 * `/admin/clients` — the registered applications (FR-OIDC-2, **D50**).
 *
 * Two kinds of client live in one table, and the difference is visible rather
 * than inferred:
 *
 * - **From the file.** Declared in `oauth_clients.jsonc` and reconciled at
 *   start-up. Read-only here, and that is the design: a form that edited one
 *   would let an administrator make a change the next restart silently undoes.
 * - **Registered here.** Marked by an owning `userId`, which is exactly the
 *   column reconciliation's orphan sweep skips — so these survive restarts and
 *   the two sets never fight over a row.
 *
 * A created client works immediately: the provider's `getClient` falls back to
 * a database lookup for ids outside its trusted-client cache, so there is no
 * restart in the loop. The one thing that does not follow automatically is the
 * origin set behind CORS and the CSP `form-action` list, which is why every
 * mutation refreshes it (`server/oidc/client-origins.ts`).
 *
 * The secret is generated by the server and shown once, through the same
 * one-shot stash the API keys use — never in the address bar.
 *
 * **Create and edit are pages** (**D93**): `/admin/clients/new` and
 * `/admin/clients/$clientId/edit`, each owning the POST it used to send here.
 * What is left on this route is the three actions that are *confirmations* —
 * enable/disable, rotate secret, remove — and the list itself. The name of a
 * database-managed row is a link to its edit page, so an addressable record is
 * reachable without opening a menu first; a file-managed name is plain text
 * beside its badge, because there is nothing to open.
 */
export const Route = createFileRoute("/admin/clients/")({
  loader: async ({ context, location }) => {
    const search = location.search as Record<string, unknown>
    return {
      ui: context.ui,
      crumbs: crumbTrail(context.ui, (t) => [
        { label: t.admin.nav.clients, to: HERE },
      ]),
      clients: (await fetchClients()) ?? [],
      notice: searchString(search.notice),
      error: searchString(search.error),
      // Claimed, and therefore consumed: this render is the only one that has
      // the secret, and the row holds nothing but a hash.
      created: await claimAdminSecret({
        data: searchString(search.created) ?? "",
      }),
    }
  },
  head: ({ loaderData }) =>
    adminHead(loaderData?.ui, (t) => t.admin.clients.title),
  component: ClientsPage,
  server: {
    handlers: {
      POST: async ({ request }) => {
        const runtime = await getRuntime()
        const base = runtime.config.base.basePath
        const here = `${base}${HERE}`

        // Read before the gate, which D63 established and **D81** kept.
        // Nothing left on this route stashes a draft — create and edit are
        // pages of their own (**D93**) — but the order is the house one and a
        // handler that reads after the gate is the one that has to remember
        // why. `readForm`, not `readFormMulti`: the repeated field was the
        // scope list, and it went with the form.
        const form = await readForm(request)

        const signedIn = await requireSession(runtime, request, HERE)
        if (!signedIn.ok) return signedIn.response

        if (form.action === "delete") {
          const result = await callAuth(
            runtime,
            "/idp/delete-client",
            { clientId: form.clientId ?? "" },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          return redirectWithCookies(`${here}?notice=clientDeleted`)
        }

        if (form.action === "toggle") {
          const result = await callAuth(
            runtime,
            "/idp/set-client-disabled",
            {
              clientId: form.clientId ?? "",
              disabled: form.disabled === "on",
            },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          return redirectWithCookies(
            `${here}?notice=${form.disabled === "on" ? "clientDisabled" : "clientEnabled"}`
          )
        }

        if (form.action === "rotate-secret") {
          const result = await callAuth(
            runtime,
            "/idp/rotate-client-secret",
            { clientId: form.clientId ?? "" },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          // The same one-shot stash a creation uses, and the same dialog on
          // the way back: a secret that travels in a query string is a secret
          // in the history, in `Referer` and in every proxy log in between.
          const rotated =
            typeof result.body.clientSecret === "string"
              ? result.body.clientSecret
              : ""
          const rotatedHandle = await stash(runtime, rotated, {
            ttlSeconds: 600,
          })
          return redirectWithCookies(`${here}?created=${rotatedHandle}`)
        }

        // Anything else is a field somebody hand-posted: this route answers
        // for the three confirmations above, and create and update moved to
        // their own pages (**D93**).
        return redirectWithCookies(withError(here, "invalid_request"))
      },
    },
  },
})

function ClientsPage() {
  const { ui, clients, notice, error, created } = Route.useLoaderData()
  const t = getCatalog(ui.locale)

  return (
    <AdminShell
      title={t.admin.clients.title}
      description={t.admin.clients.description}
      wideDescription
      actions={
        // A link, not a dialog trigger (**D93**). `/admin/clients/new` is
        // static and `$clientId` dynamic, so it can never be shadowed by an
        // application whose id happens to be `new`.
        <Link
          to="/admin/clients/new"
          className={buttonVariants({ size: "sm" })}
        >
          {t.admin.clients.add}
        </Link>
      }
    >
      <NoticeToast message={messageForNoticeCode(notice, t)} />
      <FormRefusal>
        {messageForErrorCode(error, t, ui.passwordMinLength)}
      </FormRefusal>

      {created ? (
        <SecretDialog
          t={t}
          title={t.admin.clients.secretTitle}
          description={t.admin.clients.secretHelp}
          value={created}
        />
      ) : null}

      {clients.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyDescription>{t.admin.clients.empty}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <Card className="overflow-x-auto py-0">
          <Table>
            <TableHeader>
              <TableRow>
                {/* The actions column carries no visible heading — a menu
                    button in every row needs no label above it — but a
                    `<th>` with nothing in it is a column a screen reader
                    cannot name (**D80**). First column and pinned (`sticky
                    left-0`): the table overflows its Card sideways, and a
                    menu that has to be scrolled to is a menu the owner
                    reported as invisible — on the left specifically, by the
                    owner's request (2026-08-27). Opaque background, because
                    the rest of the row passes beneath it. */}
                <TableHead className="sticky left-0 w-px bg-card">
                  <span className="sr-only">{t.admin.actions.title}</span>
                </TableHead>
                <TableHead>{t.admin.clients.name}</TableHead>
                <TableHead>{t.admin.clients.type}</TableHead>
                <TableHead>{t.admin.clients.redirectUris}</TableHead>
                <TableHead>{t.admin.clients.scopes}</TableHead>
                <TableHead>{t.admin.clients.requireConsent}</TableHead>
                <TableHead>{t.admin.clients.managedBy}</TableHead>
                <TableHead>{t.admin.clients.status}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {clients.map((client) => (
                <TableRow key={client.clientId}>
                  {/* Pinned like its header, and opaque for the same reason.
                      Opaque also swallows the row's translucent
                      `hover:bg-muted/50` / `has-aria-expanded:bg-muted/50`
                      tints, which would leave an untinted patch under the one
                      control the pointer is heading for — so the same two row
                      states repaint this cell with `--muted` pre-mixed over
                      `--card`, which is what 50 % muted composited on the
                      Card works out to. */}
                  <TableCell className="sticky left-0 bg-card transition-colors [tr:is(:hover,:has([aria-expanded=true]))_&]:bg-[color-mix(in_oklab,var(--muted)_50%,var(--card))]">
                    {/* A file-managed row has no menu at all, rather than a
                        menu of things it may not do: an edit here is one the
                        next restart would silently undo (FR-OIDC-2). */}
                    {client.managedBy === "database" ? (
                      <ClientRowActions t={t} client={client} />
                    ) : null}
                  </TableCell>
                  <TableCell>
                    {/* **D93**: the name is the way in. Edit used to exist
                        only inside the per-row `⋯`, so the whole point of an
                        addressable record was reachable only by opening a
                        menu — and the `⋯` is the first, pinned column
                        (**D80**), so linking the second restores a normal
                        left-to-right read of the row. The users list has
                        linked its e-mail column all along. A file-managed
                        name stays plain text beside its badge: there is
                        nothing to open. */}
                    {client.managedBy === "database" ? (
                      <Link
                        to="/admin/clients/$clientId/edit"
                        params={{ clientId: client.clientId }}
                        className="font-medium underline underline-offset-4"
                      >
                        {client.name}
                      </Link>
                    ) : (
                      <span className="font-medium">{client.name}</span>
                    )}
                    <code className="block text-xs text-muted-foreground">
                      {client.clientId}
                    </code>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.type}
                    <span className="block text-muted-foreground">
                      {client.isPublic
                        ? t.admin.clients.public
                        : t.admin.clients.confidential}
                    </span>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.redirectUris.map((uri) => (
                      <code key={uri} className="block break-all">
                        {uri}
                      </code>
                    ))}
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.scopes.join(" ") || "—"}
                  </TableCell>
                  {/* One affordance for both answers. It was a Badge for yes
                      and plain muted text for no, which read as two different
                      kinds of fact rather than as one column with two values
                      (round 3, finding 10) — and it named `skipConsent`, so
                      the "yes" meant the opposite of what the header
                      suggested. */}
                  <TableCell className="text-xs">
                    {client.skipConsent ? t.common.no : t.common.yes}
                  </TableCell>
                  <TableCell className="text-xs">
                    <Badge variant="outline">
                      {client.managedBy === "file"
                        ? t.admin.clients.managedFile
                        : t.admin.clients.managedDatabase}
                    </Badge>
                  </TableCell>
                  {/* Status, and only status (**D80**). The four actions
                      used to hang under this badge, which made a one-line
                      column four buttons tall and put most of a row's
                      controls under a heading that does not describe them. */}
                  <TableCell className="text-xs">
                    {client.disabled ? (
                      <Badge variant="destructive">
                        {t.admin.clients.disabled}
                      </Badge>
                    ) : (
                      <Badge variant="secondary">
                        {t.admin.clients.enabled}
                      </Badge>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}
    </AdminShell>
  )
}
