/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as Oauth2UserinfoRouteImport } from './routes/oauth2/userinfo'
import { Route as Oauth2TokenRouteImport } from './routes/oauth2/token'
import { Route as Oauth2RevokeRouteImport } from './routes/oauth2/revoke'
import { Route as Oauth2IntrospectRouteImport } from './routes/oauth2/introspect'
import { Route as Oauth2EndSessionRouteImport } from './routes/oauth2/end-session'
import { Route as Oauth2AuthorizeRouteImport } from './routes/oauth2/authorize'
import { Route as BrandingSplatRouteImport } from './routes/branding.$'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AccountSessionsRouteImport } from './routes/account/sessions'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountConsentsRouteImport } from './routes/account/consents'
import { Route as AccountApiKeysRouteImport } from './routes/account/api-keys'
import { Route as DotwellKnownSecurityDottxtRouteImport } from './routes/[.]well-known.security[.]txt'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known.jwks[.]json'
import { Route as DotwellKnownChangePasswordRouteImport } from './routes/[.]well-known.change-password'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const Oauth2UserinfoRoute = Oauth2UserinfoRouteImport.update({
  id: '/oauth2/userinfo',
  path: '/oauth2/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2TokenRoute = Oauth2TokenRouteImport.update({
  id: '/oauth2/token',
  path: '/oauth2/token',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2RevokeRoute = Oauth2RevokeRouteImport.update({
  id: '/oauth2/revoke',
  path: '/oauth2/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2IntrospectRoute = Oauth2IntrospectRouteImport.update({
  id: '/oauth2/introspect',
  path: '/oauth2/introspect',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2EndSessionRoute = Oauth2EndSessionRouteImport.update({
  id: '/oauth2/end-session',
  path: '/oauth2/end-session',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2AuthorizeRoute = Oauth2AuthorizeRouteImport.update({
  id: '/oauth2/authorize',
  path: '/oauth2/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingSplatRoute = BrandingSplatRouteImport.update({
  id: '/branding/$',
  path: '/branding/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountConsentsRoute = AccountConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => AccountRoute,
} as any)
const AccountApiKeysRoute = AccountApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AccountRoute,
} as any)
const DotwellKnownSecurityDottxtRoute =
  DotwellKnownSecurityDottxtRouteImport.update({
    id: '/.well-known/security.txt',
    path: '/.well-known/security.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownChangePasswordRoute =
  DotwellKnownChangePasswordRouteImport.update({
    id: '/.well-known/change-password',
    path: '/.well-known/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/banned': typeof BannedRoute
  '/change-password': typeof ChangePasswordRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/sign-out': typeof SignOutRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/account/api-keys': typeof AccountApiKeysRoute
  '/account/consents': typeof AccountConsentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/branding/$': typeof BrandingSplatRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/oauth2/end-session': typeof Oauth2EndSessionRoute
  '/oauth2/introspect': typeof Oauth2IntrospectRoute
  '/oauth2/revoke': typeof Oauth2RevokeRoute
  '/oauth2/token': typeof Oauth2TokenRoute
  '/oauth2/userinfo': typeof Oauth2UserinfoRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banned': typeof BannedRoute
  '/change-password': typeof ChangePasswordRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/sign-out': typeof SignOutRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/account/api-keys': typeof AccountApiKeysRoute
  '/account/consents': typeof AccountConsentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/branding/$': typeof BrandingSplatRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/oauth2/end-session': typeof Oauth2EndSessionRoute
  '/oauth2/introspect': typeof Oauth2IntrospectRoute
  '/oauth2/revoke': typeof Oauth2RevokeRoute
  '/oauth2/token': typeof Oauth2TokenRoute
  '/oauth2/userinfo': typeof Oauth2UserinfoRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/banned': typeof BannedRoute
  '/change-password': typeof ChangePasswordRoute
  '/consent': typeof ConsentRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/sign-out': typeof SignOutRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/account/api-keys': typeof AccountApiKeysRoute
  '/account/consents': typeof AccountConsentsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/branding/$': typeof BrandingSplatRoute
  '/oauth2/authorize': typeof Oauth2AuthorizeRoute
  '/oauth2/end-session': typeof Oauth2EndSessionRoute
  '/oauth2/introspect': typeof Oauth2IntrospectRoute
  '/oauth2/revoke': typeof Oauth2RevokeRoute
  '/oauth2/token': typeof Oauth2TokenRoute
  '/oauth2/userinfo': typeof Oauth2UserinfoRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/banned'
    | '/change-password'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/pending-approval'
    | '/readyz'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/sign-out'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/.well-known/change-password'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/.well-known/security.txt'
    | '/account/api-keys'
    | '/account/consents'
    | '/account/security'
    | '/account/sessions'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/roles'
    | '/admin/system'
    | '/branding/$'
    | '/oauth2/authorize'
    | '/oauth2/end-session'
    | '/oauth2/introspect'
    | '/oauth2/revoke'
    | '/oauth2/token'
    | '/oauth2/userinfo'
    | '/account/'
    | '/admin/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banned'
    | '/change-password'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/pending-approval'
    | '/readyz'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/sign-out'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/.well-known/change-password'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/.well-known/security.txt'
    | '/account/api-keys'
    | '/account/consents'
    | '/account/security'
    | '/account/sessions'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/roles'
    | '/admin/system'
    | '/branding/$'
    | '/oauth2/authorize'
    | '/oauth2/end-session'
    | '/oauth2/introspect'
    | '/oauth2/revoke'
    | '/oauth2/token'
    | '/oauth2/userinfo'
    | '/account'
    | '/admin'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/banned'
    | '/change-password'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/pending-approval'
    | '/readyz'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/sign-out'
    | '/signup'
    | '/two-factor'
    | '/verify-email'
    | '/.well-known/change-password'
    | '/.well-known/jwks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/.well-known/security.txt'
    | '/account/api-keys'
    | '/account/consents'
    | '/account/security'
    | '/account/sessions'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/roles'
    | '/admin/system'
    | '/branding/$'
    | '/oauth2/authorize'
    | '/oauth2/end-session'
    | '/oauth2/introspect'
    | '/oauth2/revoke'
    | '/oauth2/token'
    | '/oauth2/userinfo'
    | '/account/'
    | '/admin/'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BannedRoute: typeof BannedRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConsentRoute: typeof ConsentRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ReadyzRoute: typeof ReadyzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SetupRoute: typeof SetupRoute
  SignOutRoute: typeof SignOutRoute
  SignupRoute: typeof SignupRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DotwellKnownChangePasswordRoute: typeof DotwellKnownChangePasswordRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  DotwellKnownSecurityDottxtRoute: typeof DotwellKnownSecurityDottxtRoute
  BrandingSplatRoute: typeof BrandingSplatRoute
  Oauth2AuthorizeRoute: typeof Oauth2AuthorizeRoute
  Oauth2EndSessionRoute: typeof Oauth2EndSessionRoute
  Oauth2IntrospectRoute: typeof Oauth2IntrospectRoute
  Oauth2RevokeRoute: typeof Oauth2RevokeRoute
  Oauth2TokenRoute: typeof Oauth2TokenRoute
  Oauth2UserinfoRoute: typeof Oauth2UserinfoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/oauth2/userinfo': {
      id: '/oauth2/userinfo'
      path: '/oauth2/userinfo'
      fullPath: '/oauth2/userinfo'
      preLoaderRoute: typeof Oauth2UserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/token': {
      id: '/oauth2/token'
      path: '/oauth2/token'
      fullPath: '/oauth2/token'
      preLoaderRoute: typeof Oauth2TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/revoke': {
      id: '/oauth2/revoke'
      path: '/oauth2/revoke'
      fullPath: '/oauth2/revoke'
      preLoaderRoute: typeof Oauth2RevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/introspect': {
      id: '/oauth2/introspect'
      path: '/oauth2/introspect'
      fullPath: '/oauth2/introspect'
      preLoaderRoute: typeof Oauth2IntrospectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/end-session': {
      id: '/oauth2/end-session'
      path: '/oauth2/end-session'
      fullPath: '/oauth2/end-session'
      preLoaderRoute: typeof Oauth2EndSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/authorize': {
      id: '/oauth2/authorize'
      path: '/oauth2/authorize'
      fullPath: '/oauth2/authorize'
      preLoaderRoute: typeof Oauth2AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/$': {
      id: '/branding/$'
      path: '/branding/$'
      fullPath: '/branding/$'
      preLoaderRoute: typeof BrandingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/consents': {
      id: '/account/consents'
      path: '/consents'
      fullPath: '/account/consents'
      preLoaderRoute: typeof AccountConsentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/api-keys': {
      id: '/account/api-keys'
      path: '/api-keys'
      fullPath: '/account/api-keys'
      preLoaderRoute: typeof AccountApiKeysRouteImport
      parentRoute: typeof AccountRoute
    }
    '/.well-known/security.txt': {
      id: '/.well-known/security.txt'
      path: '/.well-known/security.txt'
      fullPath: '/.well-known/security.txt'
      preLoaderRoute: typeof DotwellKnownSecurityDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/change-password': {
      id: '/.well-known/change-password'
      path: '/.well-known/change-password'
      fullPath: '/.well-known/change-password'
      preLoaderRoute: typeof DotwellKnownChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountApiKeysRoute: typeof AccountApiKeysRoute
  AccountConsentsRoute: typeof AccountConsentsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountApiKeysRoute: AccountApiKeysRoute,
  AccountConsentsRoute: AccountConsentsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BannedRoute: BannedRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConsentRoute: ConsentRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ReadyzRoute: ReadyzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SetupRoute: SetupRoute,
  SignOutRoute: SignOutRoute,
  SignupRoute: SignupRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DotwellKnownChangePasswordRoute: DotwellKnownChangePasswordRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  DotwellKnownSecurityDottxtRoute: DotwellKnownSecurityDottxtRoute,
  BrandingSplatRoute: BrandingSplatRoute,
  Oauth2AuthorizeRoute: Oauth2AuthorizeRoute,
  Oauth2EndSessionRoute: Oauth2EndSessionRoute,
  Oauth2IntrospectRoute: Oauth2IntrospectRoute,
  Oauth2RevokeRoute: Oauth2RevokeRoute,
  Oauth2TokenRoute: Oauth2TokenRoute,
  Oauth2UserinfoRoute: Oauth2UserinfoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start-entry.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
