/**
 * How a client secret is stored, and the only place that decides it
 * (SEC-10, FR-OIDC-2, risk R4).
 *
 * Reconciliation writes the hash; the token endpoint verifies against it. Risk
 * R4 was that those two would disagree — that the reconciler would compute one
 * digest and Better Auth's built-in `storeClientSecret: "hashed"` another, and
 * every confidential client would fail to authenticate with the secret its own
 * config file declares. 1.7.1 accepts an explicit `{ hash, verify }` pair, so
 * the two sides are not merely compatible: they are the same function object,
 * and the risk disappears instead of being mitigated.
 *
 * **Why a plain SHA-256 rather than a password hash.** A client secret is not
 * a password. It is a ≥32-character value generated by a machine and supplied
 * through configuration (the schema refuses anything shorter), so it has full
 * entropy and no dictionary to attack — the work factor that makes bcrypt or
 * argon2 worth their cost buys nothing here, while costing every token request
 * a deliberate delay. What does matter is that the comparison cannot be timed,
 * which is what `timingSafeEqual` is for.
 */

import { createHash, timingSafeEqual } from "node:crypto"

/** SHA-256 of the secret, lower-case hex. */
export function hashClientSecret(secret: string): string {
  return createHash("sha256").update(secret, "utf8").digest("hex")
}

/**
 * Constant-time comparison of a presented secret against a stored hash.
 *
 * Length is checked first because `timingSafeEqual` throws on mismatched
 * buffers; the length of a *hash* is public, so leaking it leaks nothing.
 */
export function verifyClientSecret(
  secret: string,
  storedHash: string
): boolean {
  const expected = Buffer.from(storedHash, "hex")
  const actual = Buffer.from(hashClientSecret(secret), "hex")
  if (expected.length !== actual.length || expected.length === 0) return false
  return timingSafeEqual(expected, actual)
}

/**
 * The pair handed to `oauthProvider({ storeClientSecret })`.
 *
 * Exported as one object so a caller cannot pick up the hash without the
 * matching verify.
 */
export const clientSecretStorage = {
  hash: hashClientSecret,
  verify: verifyClientSecret,
} as const
