/**
 * The second factor (FR-2FA-1, TST-3).
 *
 * Two things are being checked. First that the challenge is real: a correct
 * password with 2FA on yields no session, only a redirect flag, and the
 * session appears exactly when the code is verified. Second that a backup code
 * works **once** — the AC that a naive "does the code match" implementation
 * passes and a correct one has to earn.
 *
 * Codes are generated by `fixtures/totp.ts`, an independent RFC 6238
 * implementation, so the test cannot agree with the server about a shared bug.
 */

import { describe, expect, it } from "vitest"

import type { TestContext } from "./harness"
import { authRequest, createTestContext, sessionCookie } from "./harness"
import { secretFromTotpUri, totpCode } from "../fixtures/totp"

const PASSWORD = "correct-horse-battery-staple"
const EMAIL = "twofactor@example.com"

async function contextWith(
  label: string,
  twoFactor: Record<string, unknown> = {}
): Promise<TestContext> {
  return createTestContext(label, {
    config: {
      signUp: { enabled: true, requireApproval: false },
      auth: { requireEmailVerification: false },
      twoFactor: { enabled: true, ...twoFactor },
    },
  })
}

/** Registers a user, signs them in, and returns the session cookie. */
async function register(context: TestContext): Promise<string> {
  const created = await context.auth.handler(
    authRequest("/sign-up/email", {
      json: { email: EMAIL, password: PASSWORD, name: "Two Factor" },
    })
  )
  expect(created.status).toBe(200)

  // Registration does not necessarily hand back a session (auto sign-in is
  // off when verification is required), so this asks for one explicitly.
  const response = await signIn(context)
  expect(response.status).toBe(200)
  const cookie = sessionCookie(response)
  expect(cookie, "sign-in should create a session").toBeTruthy()
  return cookie!
}

interface Enrolment {
  secret: string
  backupCodes: string[]
}

/**
 * Turns 2FA on and completes the enrolment.
 *
 * `/two-factor/enable` writes an *unverified* secret; the flag on the user
 * only goes up once a code from that secret has been accepted, which is what
 * stops someone locking themselves out of an account they mistyped a secret
 * into.
 */
async function enrol(context: TestContext, cookie: string): Promise<Enrolment> {
  const enabled = await context.auth.handler(
    authRequest("/two-factor/enable", {
      headers: { cookie },
      json: { password: PASSWORD },
    })
  )
  expect(enabled.status).toBe(200)
  const body = (await enabled.json()) as {
    totpURI: string
    backupCodes: string[]
  }

  const secret = secretFromTotpUri(body.totpURI)
  const verified = await context.auth.handler(
    authRequest("/two-factor/verify-totp", {
      headers: { cookie },
      json: { code: totpCode(secret) },
    })
  )
  expect(verified.status).toBe(200)

  return { secret, backupCodes: body.backupCodes }
}

/** A password sign-in. Returns the response so the caller can read the flag. */
async function signIn(context: TestContext): Promise<Response> {
  return context.auth.handler(
    authRequest("/sign-in/email", {
      json: { email: EMAIL, password: PASSWORD },
    })
  )
}

/**
 * Whether a response actually carries a session.
 *
 * `sessionCookie` also matches the **expiring** `idp.session_token=` a
 * challenge sets to clear any previous session, which is the opposite of what
 * these assertions mean.
 */
function hasSession(response: Response): boolean {
  const cookie = sessionCookie(response)
  return cookie !== undefined && !cookie.endsWith("=")
}

/** The `two_factor` challenge cookie the sign-in sets. */
function challengeCookie(response: Response): string {
  const cookies = response.headers
    .getSetCookie()
    .map((cookie) => cookie.split(";")[0])
    .filter(Boolean)
  expect(
    cookies.length,
    "the sign-in should set a challenge cookie"
  ).toBeGreaterThan(0)
  return cookies.join("; ")
}

describe("two-factor challenge", () => {
  it("answers a correct password with a challenge, not a session (FR-2FA-1)", async () => {
    const context = await contextWith("twofactor_challenge")
    try {
      const cookie = await register(context)
      const { secret } = await enrol(context, cookie)

      const response = await signIn(context)
      expect(response.status).toBe(200)
      const body = (await response.clone().json()) as {
        twoFactorRedirect?: boolean
      }
      expect(body.twoFactorRedirect).toBe(true)
      expect(hasSession(response)).toBe(false)

      const verified = await context.auth.handler(
        authRequest("/two-factor/verify-totp", {
          headers: { cookie: challengeCookie(response) },
          json: { code: totpCode(secret) },
        })
      )
      expect(verified.status).toBe(200)
      expect(hasSession(verified)).toBe(true)
    } finally {
      await context.teardown()
    }
  })

  it("refuses a wrong code and still has no session", async () => {
    const context = await contextWith("twofactor_wrong_code")
    try {
      const cookie = await register(context)
      await enrol(context, cookie)

      const response = await signIn(context)
      const rejected = await context.auth.handler(
        authRequest("/two-factor/verify-totp", {
          headers: { cookie: challengeCookie(response) },
          json: { code: "000000" },
        })
      )
      expect(rejected.status).toBeGreaterThanOrEqual(400)
      expect(hasSession(rejected)).toBe(false)
    } finally {
      await context.teardown()
    }
  })

  it("spends a backup code exactly once (TST-3)", async () => {
    const context = await contextWith("twofactor_backup_once")
    try {
      const cookie = await register(context)
      const { backupCodes } = await enrol(context, cookie)
      const code = backupCodes[0]!

      const first = await signIn(context)
      const accepted = await context.auth.handler(
        authRequest("/two-factor/verify-backup-code", {
          headers: { cookie: challengeCookie(first) },
          json: { code },
        })
      )
      expect(accepted.status).toBe(200)
      expect(hasSession(accepted)).toBe(true)

      // The same code, a fresh challenge: single-use is a property of the
      // code, not of the challenge it was spent on.
      const second = await signIn(context)
      const reused = await context.auth.handler(
        authRequest("/two-factor/verify-backup-code", {
          headers: { cookie: challengeCookie(second) },
          json: { code },
        })
      )
      expect(reused.status).toBeGreaterThanOrEqual(400)
      expect(hasSession(reused)).toBe(false)

      // A different code from the same batch still works, so the failure
      // above is single-use and not the whole batch being invalidated.
      const third = await signIn(context)
      const other = await context.auth.handler(
        authRequest("/two-factor/verify-backup-code", {
          headers: { cookie: challengeCookie(third) },
          json: { code: backupCodes[1]! },
        })
      )
      expect(other.status).toBe(200)
    } finally {
      await context.teardown()
    }
  })

  it("records the sign-in when the challenge is answered, not before (SEC-6)", async () => {
    const context = await contextWith("twofactor_audit")
    try {
      const cookie = await register(context)
      const { secret } = await enrol(context, cookie)

      // Enrolment itself signs in, so what matters is the delta.
      const before = await signInAudit(context)
      const challenge = await signIn(context)
      expect(
        await signInAudit(context),
        "a challenge is not a sign-in and must not be recorded as one"
      ).toBe(before)

      await context.auth.handler(
        authRequest("/two-factor/verify-totp", {
          headers: { cookie: challengeCookie(challenge) },
          json: { code: totpCode(secret) },
        })
      )
      expect(await signInAudit(context)).toBe(before + 1)
    } finally {
      await context.teardown()
    }
  })
})

describe("two-factor disabled", () => {
  it("registers no endpoints at all (FR-2FA-1)", async () => {
    const context = await createTestContext("twofactor_off", {
      config: {
        signUp: { enabled: true, requireApproval: false },
        auth: { requireEmailVerification: false },
        twoFactor: { enabled: false },
      },
    })
    try {
      const cookie = await register(context)
      const response = await context.auth.handler(
        authRequest("/two-factor/enable", {
          headers: { cookie },
          json: { password: PASSWORD },
        })
      )
      expect(response.status).toBe(404)
    } finally {
      await context.teardown()
    }
  })
})

/** How many `signin.success` rows the trail holds. */
async function signInAudit(context: TestContext): Promise<number> {
  const rows = await context.database.sql`
    select count(*)::int as count from ${context.database.sql(context.schemaName)}.audit_log
    where action = 'signin.success'
  `
  return (rows[0] as { count: number }).count
}
