import { createFileRoute } from "@tanstack/react-router"

import { Badge } from "@workspace/ui/components/badge"
import { Card } from "@workspace/ui/components/card"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
} from "@workspace/ui/components/empty"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@workspace/ui/components/table"

import { AdminShell } from "@/components/admin/admin-shell"
import { ClientCreateDialog } from "@/components/admin/client-create-dialog"
import { ActionDialog, SecretDialog } from "@/components/common/dialogs"
import { FormAlert } from "@/components/auth/form-parts"
import { messageForErrorCode, messageForNoticeCode } from "@/lib/auth-errors"
import { skipConsentFromForm, uriLines } from "@/lib/client-rules"
import { searchString } from "@/lib/search-params"
import { getCatalog } from "@/server/i18n"
import {
  claimAdminDraft,
  claimAdminSecret,
  fetchClients,
} from "@/server/functions/admin"
import {
  callAuth,
  errorCodeFor,
  readFormMulti,
  redirectWithCookies,
  withError,
} from "@/server/http/auth-proxy"
import { stashDraft, withDraft } from "@/server/http/draft"
import { requireFreshSession } from "@/server/http/fresh-session"
import { stash } from "@/server/http/one-shot"
import { getRuntime } from "@/server/runtime"
import { PendingForm, SubmitButton } from "@/components/common/pending-form"

const HERE = "/admin/clients"

/**
 * `/admin/clients` — the registered applications (FR-OIDC-2, **D50**).
 *
 * Two kinds of client live in one table, and the difference is visible rather
 * than inferred:
 *
 * - **From the file.** Declared in `oauth_clients.json` and reconciled at
 *   start-up. Read-only here, and that is the design: a form that edited one
 *   would let an administrator make a change the next restart silently undoes.
 * - **Registered here.** Marked by an owning `userId`, which is exactly the
 *   column reconciliation's orphan sweep skips — so these survive restarts and
 *   the two sets never fight over a row.
 *
 * A created client works immediately: the provider's `getClient` falls back to
 * a database lookup for ids outside its trusted-client cache, so there is no
 * restart in the loop. The one thing that does not follow automatically is the
 * origin set behind CORS and the CSP `form-action` list, which is why every
 * mutation refreshes it (`server/oidc/client-origins.ts`).
 *
 * The secret is generated by the server and shown once, through the same
 * one-shot stash the API keys use — never in the address bar.
 */
export const Route = createFileRoute("/admin/clients")({
  loader: async ({ context, location }) => {
    const search = location.search as Record<string, unknown>
    return {
      ui: context.ui,
      gate: context.gate,
      clients: (await fetchClients()) ?? [],
      notice: searchString(search.notice),
      error: searchString(search.error),
      // Claimed, and therefore consumed: this render is the only one that has
      // the secret, and the row holds nothing but a hash.
      created: await claimAdminSecret({
        data: searchString(search.created) ?? "",
      }),
      // The refused registration, so the dialog can reopen with what was
      // typed rather than empty (D62). Claimed, so a reload shows the form
      // the administrator is already looking at rather than an older one.
      draft:
        (await claimAdminDraft({ data: searchString(search.draft) ?? "" })) ??
        undefined,
    }
  },
  component: ClientsPage,
  server: {
    handlers: {
      POST: async ({ request }) => {
        const runtime = await getRuntime()
        const base = runtime.config.base.basePath
        const here = `${base}${HERE}`

        // **The body is read before the gate** (D63). The order used to be the
        // other way round, and FR-AUTH-5's fifteen minutes are easy to spend
        // on a twelve-field form — so a submission that arrived one minute
        // late was thrown away and retyped after signing in again. Safe to
        // reorder: `readSession` reads headers only and `callAuth` builds a
        // fresh Request, so nothing downstream wants the original stream
        // (`login.tsx` has read the body before responding since M8).
        const { fields: form, list: valuesOf } = await readFormMulti(request)

        // Registering a client is a credential-minting act, so it sits behind
        // the same freshness gate as every other admin write (FR-AUTH-5). The
        // draft rides along only for `create`: the two one-field actions have
        // nothing worth keeping, and a stale POST that is about to be refused
        // should not write a row for a client id and a hidden input.
        const fresh = await requireFreshSession(runtime, request, HERE, {
          draft:
            form.action === "delete" || form.action === "toggle"
              ? undefined
              : {
                  clientId: form.clientId,
                  name: form.name,
                  type: form.type,
                  redirectUris: form.redirectUris,
                  postLogoutRedirectUris: form.postLogoutRedirectUris,
                  scopes: valuesOf("scopes"),
                  requireConsent: form.requireConsent,
                  enableEndSession: form.enableEndSession,
                },
        })
        if (!fresh.ok) return fresh.response

        if (form.action === "delete") {
          const result = await callAuth(
            runtime,
            "/idp/delete-client",
            { clientId: form.clientId ?? "" },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, errorCodeFor(result)))
          }
          return redirectWithCookies(`${here}?notice=clientDeleted`)
        }

        if (form.action === "toggle") {
          const result = await callAuth(
            runtime,
            "/idp/set-client-disabled",
            {
              clientId: form.clientId ?? "",
              disabled: form.disabled === "on",
            },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, errorCodeFor(result)))
          }
          return redirectWithCookies(
            `${here}?notice=${form.disabled === "on" ? "clientDisabled" : "clientEnabled"}`
          )
        }

        // Create. One URI per line is what an operator actually has in front of
        // them; the schema wants an array.
        const result = await callAuth(
          runtime,
          "/idp/create-client",
          {
            clientId: form.clientId ?? "",
            name: form.name ?? "",
            type: form.type ?? "spa",
            redirectUris: uriLines(form.redirectUris ?? ""),
            postLogoutRedirectUris: uriLines(
              form.postLogoutRedirectUris ?? ""
            ),
            scopes: valuesOf("scopes"),
            // The form asks the question the other way round; the wire field
            // is unchanged (round 3, finding 10).
            skipConsent: skipConsentFromForm(form.requireConsent),
            enableEndSession: form.enableEndSession === "on",
          },
          request
        )
        if (!result.ok) {
          // What is left for the server to refuse is a duplicate id, a
          // file-managed collision or a lost race — none of which the form
          // could have known (D62). The twelve fields come back rather than
          // being retyped; nothing password-shaped is in there.
          const draft = await stashDraft(runtime, {
            clientId: form.clientId,
            name: form.name,
            type: form.type,
            redirectUris: form.redirectUris,
            postLogoutRedirectUris: form.postLogoutRedirectUris,
            scopes: valuesOf("scopes"),
            requireConsent: form.requireConsent,
            enableEndSession: form.enableEndSession,
          })
          return redirectWithCookies(
            withError(withDraft(here, draft), errorCodeFor(result))
          )
        }

        const secret =
          typeof result.body.clientSecret === "string"
            ? result.body.clientSecret
            : ""
        if (secret === "") {
          // A public client has none, so there is nothing to hand over.
          return redirectWithCookies(`${here}?notice=clientCreated`)
        }
        const handle = await stash(runtime, secret, { ttlSeconds: 600 })
        return redirectWithCookies(`${here}?created=${handle}`)
      },
    },
  },
})

function ClientsPage() {
  const { ui, gate, clients, notice, error, created, draft } =
    Route.useLoaderData()
  const t = getCatalog(ui.locale)

  return (
    <AdminShell
      ui={ui}
      t={t}
      title={t.admin.clients.title}
      description={t.admin.clients.description}
      impersonated={gate.admin ? gate.impersonated : false}
      actions={
        <ClientCreateDialog
          ui={ui}
          t={t}
          draft={draft}
          // Reopened when there is a restored form to come back to, with the
          // refusal inside it: a modal covers the page-level alert.
          reopen={draft !== undefined}
          error={
            draft !== undefined
              ? messageForErrorCode(error, t, ui.passwordMinLength)
              : undefined
          }
        />
      }
    >
      <FormAlert variant="default">{messageForNoticeCode(notice, t)}</FormAlert>
      {/* Not when the dialog is reopening with it — the modal would cover it. */}
      <FormAlert>
        {draft === undefined
          ? messageForErrorCode(error, t, ui.passwordMinLength)
          : undefined}
      </FormAlert>

      {created ? (
        <SecretDialog
          t={t}
          title={t.admin.clients.secretTitle}
          description={t.admin.clients.secretHelp}
          value={created}
        />
      ) : null}

      {clients.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyDescription>{t.admin.clients.empty}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <Card className="overflow-x-auto py-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t.admin.clients.name}</TableHead>
                <TableHead>{t.admin.clients.type}</TableHead>
                <TableHead>{t.admin.clients.redirectUris}</TableHead>
                <TableHead>{t.admin.clients.scopes}</TableHead>
                <TableHead>{t.admin.clients.requireConsent}</TableHead>
                <TableHead>{t.admin.clients.managedBy}</TableHead>
                <TableHead>{t.admin.clients.status}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {clients.map((client) => (
                <TableRow key={client.clientId}>
                  <TableCell>
                    <span className="font-medium">{client.name}</span>
                    <code className="block text-xs text-muted-foreground">
                      {client.clientId}
                    </code>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.type}
                    <span className="block text-muted-foreground">
                      {client.isPublic
                        ? t.admin.clients.public
                        : t.admin.clients.confidential}
                    </span>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.redirectUris.map((uri) => (
                      <code key={uri} className="block break-all">
                        {uri}
                      </code>
                    ))}
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.scopes.join(" ") || "—"}
                  </TableCell>
                  {/* One affordance for both answers. It was a Badge for yes
                      and plain muted text for no, which read as two different
                      kinds of fact rather than as one column with two values
                      (round 3, finding 10) — and it named `skipConsent`, so
                      the "yes" meant the opposite of what the header
                      suggested. */}
                  <TableCell className="text-xs">
                    {client.skipConsent ? t.common.no : t.common.yes}
                  </TableCell>
                  <TableCell className="text-xs">
                    <Badge variant="outline">
                      {client.managedBy === "file"
                        ? t.admin.clients.managedFile
                        : t.admin.clients.managedDatabase}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.disabled ? (
                      <Badge variant="destructive">
                        {t.admin.clients.disabled}
                      </Badge>
                    ) : (
                      <Badge variant="secondary">
                        {t.admin.clients.enabled}
                      </Badge>
                    )}
                    {client.managedBy === "database" ? (
                      <div className="mt-2 flex flex-wrap gap-2">
                        <PendingForm busy={t.common.loading} method="post">
                          <input type="hidden" name="action" value="toggle" />
                          <input
                            type="hidden"
                            name="clientId"
                            value={client.clientId}
                          />
                          {client.disabled ? null : (
                            <input type="hidden" name="disabled" value="on" />
                          )}
                          <SubmitButton variant="outline" size="sm">
                            {client.disabled
                              ? t.admin.clients.enable
                              : t.admin.clients.disable}
                          </SubmitButton>
                        </PendingForm>
                        <ActionDialog
                          label={t.admin.clients.remove}
                          description={t.admin.clients.removeConfirm}
                          variant="destructive"
                        >
                          <PendingForm
                            busy={t.common.loading}
                            method="post"
                            className="grid gap-4"
                          >
                            <input type="hidden" name="action" value="delete" />
                            <input
                              type="hidden"
                              name="clientId"
                              value={client.clientId}
                            />
                            <SubmitButton variant="destructive">
                              {t.admin.clients.remove}
                            </SubmitButton>
                          </PendingForm>
                        </ActionDialog>
                      </div>
                    ) : null}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}
    </AdminShell>
  )
}
