import { createFileRoute } from "@tanstack/react-router"

import { Badge } from "@workspace/ui/components/badge"
import { Card } from "@workspace/ui/components/card"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
} from "@workspace/ui/components/empty"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@workspace/ui/components/table"

import { AdminShell } from "@/components/admin/admin-shell"
import { ClientCreateDialog } from "@/components/admin/client-create-dialog"
import { ClientRowActions } from "@/components/admin/client-row-actions"
import { SecretDialog } from "@/components/common/dialogs"
import { FormAlert } from "@/components/auth/form-parts"
import { NoticeToast } from "@/components/common/notice-toast"
import { messageForErrorCode, messageForNoticeCode } from "@/lib/auth-errors"
import { skipConsentFromForm, uriLines } from "@/lib/client-rules"
import { searchString } from "@/lib/search-params"
import { getCatalog } from "@/server/i18n"
import {
  claimAdminDraft,
  claimAdminSecret,
  fetchClients,
} from "@/server/functions/admin"
import {
  adminErrorCodeFor,
  callAuth,
  readFormMulti,
  redirectWithCookies,
  withError,
} from "@/server/http/auth-proxy"
import { stashDraft, withDraft } from "@/server/http/draft"
import type { Draft } from "@/server/http/draft"
import { requireSession } from "@/server/http/require-session"
import { stash } from "@/server/http/one-shot"
import { getRuntime } from "@/server/runtime"

const HERE = "/admin/clients"

/**
 * `/admin/clients` — the registered applications (FR-OIDC-2, **D50**).
 *
 * Two kinds of client live in one table, and the difference is visible rather
 * than inferred:
 *
 * - **From the file.** Declared in `oauth_clients.jsonc` and reconciled at
 *   start-up. Read-only here, and that is the design: a form that edited one
 *   would let an administrator make a change the next restart silently undoes.
 * - **Registered here.** Marked by an owning `userId`, which is exactly the
 *   column reconciliation's orphan sweep skips — so these survive restarts and
 *   the two sets never fight over a row.
 *
 * A created client works immediately: the provider's `getClient` falls back to
 * a database lookup for ids outside its trusted-client cache, so there is no
 * restart in the loop. The one thing that does not follow automatically is the
 * origin set behind CORS and the CSP `form-action` list, which is why every
 * mutation refreshes it (`server/oidc/client-origins.ts`).
 *
 * The secret is generated by the server and shown once, through the same
 * one-shot stash the API keys use — never in the address bar.
 */
export const Route = createFileRoute("/admin/clients")({
  loader: async ({ context, location }) => {
    const search = location.search as Record<string, unknown>
    return {
      ui: context.ui,
      clients: (await fetchClients()) ?? [],
      notice: searchString(search.notice),
      error: searchString(search.error),
      // Claimed, and therefore consumed: this render is the only one that has
      // the secret, and the row holds nothing but a hash.
      created: await claimAdminSecret({
        data: searchString(search.created) ?? "",
      }),
      // The refused registration, so the dialog can reopen with what was
      // typed rather than empty (D62). Claimed, so a reload shows the form
      // the administrator is already looking at rather than an older one.
      draft:
        (await claimAdminDraft({ data: searchString(search.draft) ?? "" })) ??
        undefined,
    }
  },
  component: ClientsPage,
  server: {
    handlers: {
      POST: async ({ request }) => {
        const runtime = await getRuntime()
        const base = runtime.config.base.basePath
        const here = `${base}${HERE}`

        // Read before the gate, which D63 established and **D81** kept: a
        // refusal that arrives with the body already in hand can stash the
        // draft, and the error paths below still do. Safe because
        // `readSession` reads headers only and `callAuth` builds a fresh
        // Request, so nothing downstream wants the original stream.
        const { fields: form, list: valuesOf } = await readFormMulti(request)

        const signedIn = await requireSession(runtime, request, HERE)
        if (!signedIn.ok) return signedIn.response

        if (form.action === "delete") {
          const result = await callAuth(
            runtime,
            "/idp/delete-client",
            { clientId: form.clientId ?? "" },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          return redirectWithCookies(`${here}?notice=clientDeleted`)
        }

        if (form.action === "toggle") {
          const result = await callAuth(
            runtime,
            "/idp/set-client-disabled",
            {
              clientId: form.clientId ?? "",
              disabled: form.disabled === "on",
            },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          return redirectWithCookies(
            `${here}?notice=${form.disabled === "on" ? "clientDisabled" : "clientEnabled"}`
          )
        }

        if (form.action === "rotate-secret") {
          const result = await callAuth(
            runtime,
            "/idp/rotate-client-secret",
            { clientId: form.clientId ?? "" },
            request
          )
          if (!result.ok) {
            return redirectWithCookies(withError(here, adminErrorCodeFor(result)))
          }
          // The same one-shot stash a creation uses, and the same dialog on
          // the way back: a secret that travels in a query string is a secret
          // in the history, in `Referer` and in every proxy log in between.
          const rotated =
            typeof result.body.clientSecret === "string"
              ? result.body.clientSecret
              : ""
          const rotatedHandle = await stash(runtime, rotated, {
            ttlSeconds: 600,
          })
          return redirectWithCookies(`${here}?created=${rotatedHandle}`)
        }

        // Create and update marshal identically — `/idp/update-client` takes
        // create's body, because a full replace *is* a create against a row
        // that already exists (D72).
        const updating = form.action === "update"
        const result = await callAuth(
          runtime,
          updating ? "/idp/update-client" : "/idp/create-client",
          {
            clientId: form.clientId ?? "",
            name: form.name ?? "",
            type: form.type ?? "spa",
            redirectUris: uriLines(form.redirectUris ?? ""),
            postLogoutRedirectUris: uriLines(
              form.postLogoutRedirectUris ?? ""
            ),
            scopes: valuesOf("scopes"),
            // The form asks the question the other way round; the wire field
            // is unchanged (round 3, finding 10).
            skipConsent: skipConsentFromForm(form.requireConsent),
            enableEndSession: form.enableEndSession === "on",
          },
          request
        )
        if (!result.ok) {
          // What is left for the server to refuse is a duplicate id, a
          // file-managed collision or a lost race — none of which the form
          // could have known (D62). The twelve fields come back rather than
          // being retyped; nothing password-shaped is in there.
          const draft = await stashDraft(runtime, {
            // Which dialog reopens. An edit dialog exists per row, so the id
            // is what tells them apart — without it, every row's dialog would
            // reopen carrying one row's rejected values (D72).
            action: form.action,
            clientId: form.clientId,
            name: form.name,
            type: form.type,
            redirectUris: form.redirectUris,
            postLogoutRedirectUris: form.postLogoutRedirectUris,
            scopes: valuesOf("scopes"),
            requireConsent: form.requireConsent,
            enableEndSession: form.enableEndSession,
          })
          return redirectWithCookies(
            withError(withDraft(here, draft), adminErrorCodeFor(result))
          )
        }

        const secret =
          typeof result.body.clientSecret === "string"
            ? result.body.clientSecret
            : ""
        if (secret === "") {
          // Nothing to hand over, for one of two reasons, and **which one
          // matters** (**D78**). A public client has no secret at all: the
          // form's default type is `spa`, so the commonest registration on
          // this page produced "The application has been registered." and no
          // secret dialog, and the operator had no way to tell that from a
          // failure to show one. An update that kept the existing secret is
          // the other reason, and deliberately does not re-show it — the row
          // holds a hash. The endpoint answers `isPublic` for exactly this.
          const isPublic = result.body.isPublic === true
          const notice = updating
            ? isPublic
              ? "clientUpdatedPublic"
              : "clientUpdated"
            : isPublic
              ? "clientCreatedPublic"
              : "clientCreated"
          return redirectWithCookies(`${here}?notice=${notice}`)
        }
        const handle = await stash(runtime, secret, { ttlSeconds: 600 })
        return redirectWithCookies(`${here}?created=${handle}`)
      },
    },
  },
})

function ClientsPage() {
  const { ui, clients, notice, error, created, draft } = Route.useLoaderData()
  const t = getCatalog(ui.locale)
  // One draft handle, several dialogs that could claim it (**D72**).
  // `action` says which; absent means create, so a draft stashed before edit
  // existed still lands where it came from.
  const createDraft = draft?.action === "update" ? undefined : draft
  const editDraftFor = (clientId: string): Draft | undefined =>
    draft?.action === "update" && draft.clientId === clientId
      ? draft
      : undefined

  return (
    <AdminShell
      title={t.admin.clients.title}
      description={t.admin.clients.description}
      actions={
        <ClientCreateDialog
          ui={ui}
          t={t}
          draft={createDraft}
          // Reopened when there is a restored form to come back to, with the
          // refusal inside it: a modal covers the page-level alert.
          reopen={createDraft !== undefined}
          error={
            createDraft !== undefined
              ? messageForErrorCode(error, t, ui.passwordMinLength)
              : undefined
          }
        />
      }
    >
      <NoticeToast message={messageForNoticeCode(notice, t)} />
      {/* Not when the dialog is reopening with it — the modal would cover it. */}
      <FormAlert>
        {draft === undefined
          ? messageForErrorCode(error, t, ui.passwordMinLength)
          : undefined}
      </FormAlert>

      {created ? (
        <SecretDialog
          t={t}
          title={t.admin.clients.secretTitle}
          description={t.admin.clients.secretHelp}
          value={created}
        />
      ) : null}

      {clients.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyDescription>{t.admin.clients.empty}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <Card className="overflow-x-auto py-0">
          <Table>
            <TableHeader>
              <TableRow>
                {/* The actions column carries no visible heading — a menu
                    button in every row needs no label above it — but a
                    `<th>` with nothing in it is a column a screen reader
                    cannot name (**D80**). First column and pinned (`sticky
                    left-0`): the table overflows its Card sideways, and a
                    menu that has to be scrolled to is a menu the owner
                    reported as invisible — on the left specifically, by the
                    owner's request (2026-08-27). Opaque background, because
                    the rest of the row passes beneath it. */}
                <TableHead className="sticky left-0 w-px bg-card">
                  <span className="sr-only">{t.admin.actions.title}</span>
                </TableHead>
                <TableHead>{t.admin.clients.name}</TableHead>
                <TableHead>{t.admin.clients.type}</TableHead>
                <TableHead>{t.admin.clients.redirectUris}</TableHead>
                <TableHead>{t.admin.clients.scopes}</TableHead>
                <TableHead>{t.admin.clients.requireConsent}</TableHead>
                <TableHead>{t.admin.clients.managedBy}</TableHead>
                <TableHead>{t.admin.clients.status}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {clients.map((client) => (
                <TableRow key={client.clientId}>
                  {/* Pinned like its header, and opaque for the same reason.
                      Opaque also swallows the row's translucent
                      `hover:bg-muted/50` / `has-aria-expanded:bg-muted/50`
                      tints, which would leave an untinted patch under the one
                      control the pointer is heading for — so the same two row
                      states repaint this cell with `--muted` pre-mixed over
                      `--card`, which is what 50 % muted composited on the
                      Card works out to. */}
                  <TableCell className="sticky left-0 bg-card transition-colors [tr:is(:hover,:has([aria-expanded=true]))_&]:bg-[color-mix(in_oklab,var(--muted)_50%,var(--card))]">
                    {/* A file-managed row has no menu at all, rather than a
                        menu of things it may not do: an edit here is one the
                        next restart would silently undo (FR-OIDC-2). */}
                    {client.managedBy === "database" ? (
                      <ClientRowActions
                        ui={ui}
                        t={t}
                        client={client}
                        draft={editDraftFor(client.clientId)}
                        error={
                          editDraftFor(client.clientId) !== undefined
                            ? messageForErrorCode(
                                error,
                                t,
                                ui.passwordMinLength
                              )
                            : undefined
                        }
                      />
                    ) : null}
                  </TableCell>
                  <TableCell>
                    <span className="font-medium">{client.name}</span>
                    <code className="block text-xs text-muted-foreground">
                      {client.clientId}
                    </code>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.type}
                    <span className="block text-muted-foreground">
                      {client.isPublic
                        ? t.admin.clients.public
                        : t.admin.clients.confidential}
                    </span>
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.redirectUris.map((uri) => (
                      <code key={uri} className="block break-all">
                        {uri}
                      </code>
                    ))}
                  </TableCell>
                  <TableCell className="text-xs">
                    {client.scopes.join(" ") || "—"}
                  </TableCell>
                  {/* One affordance for both answers. It was a Badge for yes
                      and plain muted text for no, which read as two different
                      kinds of fact rather than as one column with two values
                      (round 3, finding 10) — and it named `skipConsent`, so
                      the "yes" meant the opposite of what the header
                      suggested. */}
                  <TableCell className="text-xs">
                    {client.skipConsent ? t.common.no : t.common.yes}
                  </TableCell>
                  <TableCell className="text-xs">
                    <Badge variant="outline">
                      {client.managedBy === "file"
                        ? t.admin.clients.managedFile
                        : t.admin.clients.managedDatabase}
                    </Badge>
                  </TableCell>
                  {/* Status, and only status (**D80**). The four actions
                      used to hang under this badge, which made a one-line
                      column four buttons tall and put most of a row's
                      controls under a heading that does not describe them. */}
                  <TableCell className="text-xs">
                    {client.disabled ? (
                      <Badge variant="destructive">
                        {t.admin.clients.disabled}
                      </Badge>
                    ) : (
                      <Badge variant="secondary">
                        {t.admin.clients.enabled}
                      </Badge>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}
    </AdminShell>
  )
}
