//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    // Every component in `src/components` is copied from the shadcn registry
    // and re-copied whenever a preset is applied. These are `tanstackConfig`
    // opinions that the registry's own output does not share, so leaving them
    // on means hand-patching generated files after every `shadcn add` — and
    // the patch is undone by the next one.
    rules: {
      // Registry components write `import { cva, type VariantProps }`.
      "import/consistent-type-specifier-style": "off",
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      // `field.tsx` writes `uniqueErrors?.length` over an array it just built.
      // Belt-and-braces in the registry's own style; the rule is what has to
      // give, because the file is regenerated by the next `add`.
      "@typescript-eslint/no-unnecessary-condition": "off",
      // `sidebar.tsx`'s `setOpen` takes `boolean | ((open: boolean) => boolean)`
      // and names the callback parameter `open` inside a closure that already
      // has one. Shadowing is the registry's own style here and the file is
      // regenerated by the next `add`.
      "no-shadow": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    ignores: ["eslint.config.js", ".prettierrc"],
  },
]
